# Generated by Django 3.2 on 2023-09-14 07:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
        ('products', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Storage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180, verbose_name='Наименование')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.company', verbose_name='Компания')),
            ],
            options={
                'verbose_name': 'Склад',
                'verbose_name_plural': 'Склады',
            },
        ),
        migrations.CreateModel(
            name='StorageOperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation_method', models.CharField(choices=[('COMING', 'Приход'), ('WRITE_OFF', 'Списание'), ('MOVING_REPLENISHMENT', 'Перемещение пополнение'), ('MOVING_WRITE_OFF', 'Перемещение списание')], max_length=30, verbose_name='Вид операции')),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content_type', models.ForeignKey(blank=True, limit_choices_to={'model__in': ('user', 'contractor')}, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('storage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse.storage')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StorageOperationMove',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField(default=1)),
                ('description', models.TextField(blank=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.company', verbose_name='Компания')),
                ('storage_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sm_storage_from', to='warehouse.storage', verbose_name='Из склада')),
                ('storage_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sm_storage_to', to='warehouse.storage', verbose_name='В склад')),
            ],
        ),
        migrations.CreateModel(
            name='StorageOperationDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('quantity', models.FloatField(default=1)),
                ('content_type', models.ForeignKey(limit_choices_to={'model__in': ('material', 'product')}, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('storage_operation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='storage_operation_details', to='warehouse.storageoperation')),
            ],
        ),
        migrations.CreateModel(
            name='Contractor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180, verbose_name='Наименование')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warehouse_contractors', to='account.company', verbose_name='Компания')),
            ],
            options={
                'verbose_name': 'Контрагент',
                'verbose_name_plural': 'Контрагенты',
            },
        ),
        migrations.CreateModel(
            name='Consumable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consumption', models.FloatField(default=0)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.material')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
                ('storage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse.storage')),
            ],
        ),
    ]
