# Generated by Django 3.2 on 2023-09-14 07:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week', models.PositiveSmallIntegerField(choices=[(0, 'Пн'), (1, 'Втр'), (2, 'Срд'), (3, 'Чтв'), (4, 'Птн'), (5, 'Суб'), (6, 'Воск')], default=0)),
                ('status', models.CharField(choices=[('working', 'Рабочий день'), ('day_off', 'Выходной')], default='working', max_length=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('working', 'Работает'), ('day_off', 'Выходной'), ('holiday', 'Праздничный'), ('absent', 'Прогул')], default='working', max_length=10)),
                ('date', models.DateField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='worktime',
            constraint=models.UniqueConstraint(fields=('week', 'user'), name='unique_week_user'),
        ),
    ]
