# Generated by Django 3.2 on 2023-09-14 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work_time', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worktime',
            name='status',
            field=models.CharField(choices=[('working', 'Рабочий день'), ('non-working', 'Выходной')], default='working', max_length=80),
        ),
    ]
