# Generated by Django 3.2 on 2023-09-18 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('work_time', '0002_alter_worktime_status'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='worktime',
            name='unique_week_user',
        ),
    ]
