# Generated by Django 3.2 on 2023-09-14 07:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SalarySetup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bonus_type', models.CharField(choices=[('fixed_payment', 'Фиксированная оплата'), ('percentage_payment', 'Оплата по проценту')], max_length=80)),
                ('bonus', models.FloatField()),
                ('salary', models.DecimalField(decimal_places=0, max_digits=19)),
                ('salary_type', models.CharField(choices=[('fixed', 'Фиксированная зарплата'), ('percentage', 'Процентная ставка')], default='fixed', max_length=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SalaryAdvance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('advance', models.DecimalField(decimal_places=0, max_digits=19)),
                ('comment', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Salary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed_amount', models.DecimalField(decimal_places=0, max_digits=19)),
                ('salary', models.DecimalField(decimal_places=0, max_digits=19)),
                ('bonus_type', models.CharField(choices=[('fixed_payment', 'Фиксированная оплата'), ('percentage_payment', 'Оплата по проценту')], max_length=80)),
                ('bonus', models.FloatField()),
                ('advance_bonus', models.DecimalField(decimal_places=0, default=0, max_digits=19)),
                ('comment', models.TextField(blank=True, null=True)),
                ('penalty', models.DecimalField(decimal_places=0, default=0, max_digits=19)),
                ('pension_contribution', models.DecimalField(decimal_places=0, default=0, max_digits=19)),
                ('advance_payment', models.DecimalField(decimal_places=0, default=0, max_digits=19)),
                ('month_year', models.DateField()),
                ('is_full_payment', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Penalty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('penalty', models.DecimalField(decimal_places=0, max_digits=19)),
                ('comment', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
