# Generated by Django 3.2 on 2023-09-18 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='salary',
            old_name='bonus',
            new_name='premium',
        ),
        migrations.RenameField(
            model_name='salarysetup',
            old_name='bonus',
            new_name='premium',
        ),
        migrations.RemoveField(
            model_name='salary',
            name='bonus_type',
        ),
        migrations.RemoveField(
            model_name='salarysetup',
            name='bonus_type',
        ),
        migrations.AddField(
            model_name='salary',
            name='salary_type',
            field=models.CharField(choices=[('salary', 'Оклад'), ('salary_fixed_premium', 'Оклад + фиксированная надбавка'), ('salary_percentage_premium', 'Оклад + процентная надбавка'), ('percentage', 'Процентная оплата')], default='salary', max_length=80),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='salarysetup',
            name='salary_type',
            field=models.CharField(choices=[('salary', 'Оклад'), ('salary_fixed_premium', 'Оклад + фиксированная надбавка'), ('salary_percentage_premium', 'Оклад + процентная надбавка'), ('percentage', 'Процентная оплата')], max_length=80),
        ),
    ]
