# Generated by Django 3.2 on 2023-09-18 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0002_auto_20230918_1326'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SalaryAdvance',
        ),
    ]
