# Generated by Django 3.2 on 2023-09-18 09:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
        ('payroll', '0003_delete_salaryadvance'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductBonus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bonus_fixed', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('bonus_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
        ),
    ]
