# Generated by Django 3.2 on 2023-09-18 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0004_productbonus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productbonus',
            name='bonus_fixed',
        ),
        migrations.RemoveField(
            model_name='productbonus',
            name='bonus_percentage',
        ),
        migrations.AddField(
            model_name='productbonus',
            name='bonus_type',
            field=models.CharField(choices=[('fixed', 'Фиксированный бонус'), ('percentage', 'Процентный бонус')], default='fixed', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
             model_name='productbonus',
             name='bonus_value',
             field=models.DecimalField(decimal_places=2, default=0.00, max_digits=8),
             preserve_default=False,
        ),
    ]
