# Generated by Django 3.2 on 2023-09-14 07:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=320)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('field_type', models.CharField(choices=[('text', 'Ввод текста'), ('number', 'Число'), ('textarea', 'textarea'), ('select', 'select'), ('datalist', 'datalist'), ('checkbox', 'checkbox'), ('radio', 'radio'), ('inline_field', 'Встроенное поле'), ('date', 'Дата'), ('accepting_payment', 'Принятие оплаты'), ('payment_after_commission', 'Сумма после комиссии'), ('payment_method', 'Способ оплаты'), ('payment_confirmation', 'Подтверждение оплаты'), ('surcharge', 'Доплата'), ('discount', 'Скидка'), ('discounted_amount', 'Сумма со скидкой'), ('total_payment', 'Общая сумма к оплате'), ('remainder', 'Остаток оплаты'), ('bank', 'Банк'), ('material_by_category', 'Материал по категориям'), ('receipt_amount', 'Сумма поступления')], max_length=100)),
                ('choices', models.JSONField(blank=True, default=dict, null=True)),
                ('is_required', models.BooleanField(default=False)),
                ('associated_object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('color', models.CharField(blank=True, max_length=15, null=True)),
                ('styles', models.CharField(blank=True, max_length=320, null=True)),
                ('sorting', models.PositiveIntegerField(default=0)),
                ('is_select2', models.BooleanField(default=False)),
                ('associated_blocking_field', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blocked_by', to='dynamic_forms.formfield')),
                ('associated_content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='associated_content_type_by', to='contenttypes.contenttype')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.company')),
                ('content_type', models.ForeignKey(limit_choices_to={'model__in': ('card', 'order', 'orderproduct')}, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
        ),
        migrations.CreateModel(
            name='FormFieldPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type', models.PositiveSmallIntegerField(choices=[(1, 'Администратор'), (2, 'Главный менеджер'), (3, 'Менеджер'), (4, 'Логистика'), (5, 'Мастер'), (6, 'Бухгалтер'), (7, 'Владелец'), (8, 'Супервайзер производства'), (9, 'Дизайнер')])),
                ('permission', models.CharField(choices=[('full', 'Полный доступ'), ('read_only', 'Только чтение')], default='full', max_length=10)),
                ('sorting', models.IntegerField(default=0)),
                ('form_field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dynamic_forms.formfield')),
            ],
            options={
                'ordering': ['sorting'],
            },
        ),
        migrations.CreateModel(
            name='DynamicFormData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=320)),
                ('field_value', models.CharField(max_length=320)),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(limit_choices_to={'model__in': ('card', 'order', 'orderproduct')}, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
        ),
    ]
