# Generated by Django 4.2 on 2024-01-20 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic_forms', '0002_alter_formfield_name_alter_formfield_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='formfield',
            name='classes',
            field=models.CharField(blank=True, max_length=320, null=True),
        ),
    ]
