# Generated by Django 4.2 on 2024-01-23 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic_forms', '0004_alter_formfield_field_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formfield',
            name='field_type',
            field=models.CharField(choices=[('text', 'Ввод текста'), ('number', 'Число'), ('textarea', 'textarea'), ('select', 'select'), ('datalist', 'datalist'), ('checkbox', 'checkbox'), ('radio', 'radio'), ('inline_field', 'Встроенное поле'), ('date', 'Дата'), ('accepting_payment', 'Принятие оплаты'), ('payment_after_commission', 'Сумма после комиссии'), ('payment_method', 'Способ оплаты'), ('payment_confirmation', 'Подтверждение оплаты'), ('surcharge', 'Доплата'), ('discount', 'Скидка'), ('discounted_amount', 'Сумма со скидкой'), ('total_payment', 'Общая сумма к оплате'), ('remainder', 'Остаток оплаты'), ('bank', 'Банк'), ('material_by_category', 'Материал по категориям'), ('receipt_amount', 'Сумма поступления'), ('delivery_consumption', 'Расходы доставки')], max_length=100),
        ),
    ]
