# Generated by Django 4.2 on 2024-01-26 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic_forms', '0005_alter_formfield_field_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formfield',
            name='field_type',
            field=models.CharField(choices=[('text', 'Ввод текста'), ('number', 'Число'), ('textarea', 'textarea'), ('select', 'select'), ('datalist', 'datalist'), ('checkbox', 'checkbox'), ('radio', 'radio'), ('inline_field', 'Встроенное поле'), ('date', 'Дата'), ('accepting_payment', 'Принятие оплаты'), ('payment_after_commission', 'Сумма после комиссии'), ('payment_method', 'Способ оплаты'), ('payment_confirmation', 'Подтверждение оплаты'), ('surcharge', 'Доплата'), ('discount', 'Скидка'), ('discounted_amount', 'Сумма со скидкой'), ('total_payment', 'Общая сумма к оплате'), ('remainder', 'Остаток оплаты'), ('bank', 'Банк'), ('material_by_category', 'Материал по категориям'), ('receipt_amount', 'Сумма поступления'), ('delivery_consumption', 'Расходы доставки'), ('salesman', 'Оптовики')], max_length=100),
        ),
        migrations.AlterField(
            model_name='formfieldpermission',
            name='user_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Администратор'), (2, 'Главный менеджер'), (3, 'Менеджер'), (4, 'Логистика'), (5, 'Мастер'), (6, 'Бухгалтер'), (10, 'Бухгалтер оптавиков'), (7, 'Владелец'), (8, 'Супервайзер производства'), (9, 'Дизайнер')]),
        ),
    ]
