# Generated by Django 4.2 on 2024-01-26 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic_forms', '0006_alter_formfield_field_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formfieldpermission',
            name='user_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Администратор'), (2, 'Главный менеджер'), (3, 'Менеджер'), (4, 'Логистика'), (5, 'Мастер'), (6, 'Бухгалтер'), (10, 'Бухгалтер оптавиков'), (7, 'Владелец'), (8, 'Супервайзер производства'), (9, 'Дизайнер'), (11, 'Оптовик')]),
        ),
    ]
