# Generated by Django 3.2 on 2023-09-18 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='extra_data',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
