# Generated by Django 3.2 on 2023-09-14 07:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180, verbose_name='Наименование')),
                ('commission', models.FloatField()),
                ('bank', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='accounting.paymentmethod', verbose_name='Банк')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.company', verbose_name='Компания')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation_method', models.CharField(choices=[('PURCHASE_MATERIAL', 'Закупка материалов'), ('STAFF_SALARY', 'Зарплата персонала'), ('TAXES_FEES', 'Налоги и сборы'), ('SALE_GOOD', 'Продажа товара'), ('OTHER_EXPENSES', 'Прочие расходы'), ('OTHER_INCOME', 'Прочие доходы'), ('TRANSFER_REPLENISHMENT', 'Перевод пополнение'), ('TRANSFER_WRITE_OFF', 'Перевод списание'), ('PREPAID_EXPENSE', 'Аванс')], max_length=30, verbose_name='Вид операции')),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content_type', models.ForeignKey(blank=True, limit_choices_to={'model__in': ('user', 'contractor', 'customer', 'order', 'transactionmove', 'salary')}, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TransactionMove',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=0, max_digits=19)),
                ('description', models.TextField(blank=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.company', verbose_name='Компания')),
                ('payment_method_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tm_payment_methods_from', to='accounting.paymentmethod', verbose_name='Из кассы')),
                ('payment_method_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tm_payment_methods_to', to='accounting.paymentmethod', verbose_name='В кассу')),
            ],
        ),
        migrations.CreateModel(
            name='TransactionDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commission', models.FloatField(blank=True, null=True, verbose_name='Комиссия')),
                ('price', models.DecimalField(decimal_places=0, max_digits=19)),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('content_type', models.ForeignKey(blank=True, limit_choices_to={'model__in': ('formfield',)}, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('payment_method', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.paymentmethod', verbose_name='Способ оплаты')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transaction_details', to='accounting.transaction', verbose_name='Транзакция')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentMethodCommission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commission', models.FloatField()),
                ('date', models.DateField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.company', verbose_name='Компания')),
                ('payment_method', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.paymentmethod')),
            ],
        ),
        migrations.CreateModel(
            name='Contractor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180, verbose_name='Наименование')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.company', verbose_name='Компания')),
            ],
            options={
                'verbose_name': 'Контрагент',
                'verbose_name_plural': 'Контрагенты',
            },
        ),
        migrations.AddConstraint(
            model_name='transaction',
            constraint=models.UniqueConstraint(fields=('content_type', 'object_id', 'operation_method'), name='unique_item'),
        ),
    ]
