# Generated by Django 4.2 on 2024-01-23 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='operation_method',
            field=models.CharField(choices=[('PURCHASE_MATERIAL', 'Закупка материалов'), ('STAFF_SALARY', 'Зарплата персонала'), ('TAXES_FEES', 'Налоги и сборы'), ('SALE_GOOD', 'Продажа товара'), ('DELIVERY_CONSUMPTION', 'Расходы доставки'), ('OTHER_EXPENSES', 'Прочие расходы'), ('OTHER_INCOME', 'Прочие доходы'), ('TRANSFER_REPLENISHMENT', 'Перевод пополнение'), ('TRANSFER_WRITE_OFF', 'Перевод списание'), ('PREPAID_EXPENSE', 'Аванс')], max_length=30, verbose_name='Вид операции'),
        ),
    ]
