# Generated by Django 3.2 on 2023-09-14 07:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=320)),
                ('comment', models.TextField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_product', to='account.company')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=320)),
                ('comment', models.TextField(blank=True, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=1, max_digits=8, null=True)),
                ('actual_price', models.DecimalField(blank=True, decimal_places=1, max_digits=8, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.company')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MaterialCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=320)),
                ('comment', models.TextField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.company')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=320)),
                ('comment', models.TextField(blank=True, null=True)),
                ('barcode', models.CharField(blank=True, max_length=180, null=True)),
                ('sale_unit', models.IntegerField(choices=[(1, 'шт'), (2, 'миллилитр'), (3, 'грамм'), (4, 'упаковка'), (5, 'миллиграмм'), (6, 'сантиметр'), (7, 'микролитр'), (9, 'сетр'), (10, 'рулон'), (11, 'литр'), (12, 'флакон'), (13, 'единица'), (14, 'килограмм'), (15, 'ампула'), (16, 'коробка'), (17, 'капсула'), (18, 'доза'), (19, 'другое')], default=0)),
                ('write_off_unit', models.IntegerField(choices=[(1, 'шт'), (2, 'миллилитр'), (3, 'грамм'), (4, 'упаковка'), (5, 'миллиграмм'), (6, 'сантиметр'), (7, 'микролитр'), (9, 'сетр'), (10, 'рулон'), (11, 'литр'), (12, 'флакон'), (13, 'единица'), (14, 'килограмм'), (15, 'ампула'), (16, 'коробка'), (17, 'капсула'), (18, 'доза'), (19, 'другое')], default=0)),
                ('unit_equals', models.IntegerField(default=0)),
                ('price', models.DecimalField(blank=True, decimal_places=1, max_digits=8, null=True)),
                ('actual_price', models.DecimalField(blank=True, decimal_places=1, max_digits=8, null=True)),
                ('critical_amount', models.IntegerField(blank=True, default=0, null=True)),
                ('desired_amount', models.IntegerField(blank=True, default=0, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.materialcategory')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
